# Generated by Django 4.2.3 on 2023-07-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('category', models.IntegerField(choices=[(1, 'Birthday'), (2, 'Sports'), (3, 'Conferences'), (4, 'Expos'), (5, 'Concerts'), (6, 'Concerts'), (7, 'Festivals'), (8, 'Performing Arts')])),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('amenities', models.CharField(max_length=500)),
                ('availability', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Reject'), (1, 'Accept')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venue'),
        ),
    ]
